baseURL = "https://svemagie.net"
title = "svemagie.net"
theme = ["zzo"]
publishDir = "docs"
buildDrafts = true

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean languages.

summaryLength = 30 # The length of a post description on a list page.
buildFuture = true # if true, we can use future date for talks page

copyright = "©{year} All Rights Reserved | Use of our site and other services are at your own risk!"
timeout = 10000
enableEmoji = true
paginate = 13 # Number of items per page in paginated lists.
rssLimit = 15

enableGitInfo = false
googleAnalytics = ""

[markup]
  [markup.goldmark]
   [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  confidence = "confidence"
  importance = "importance"
